# Generated by Django 4.2.8 on 2025-03-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='profile_picture',
        ),
    ]
