# Generated by Django 4.2.8 on 2025-04-01 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_updated', 'Booking Updated'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('user_registered', 'User Registered'), ('user_updated', 'User Updated'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_deleted', 'Event Deleted'), ('subevent_created', 'Subevent Created'), ('subevent_updated', 'Subevent Updated'), ('subevent_deleted', 'Subevent Deleted'), ('gallery_updated', 'Gallery Updated'), ('message_sent', 'Message Sent'), ('review_posted', 'Review Posted'), ('admin_action', 'Admin Action')], max_length=50)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
