# Generated by Django 4.2.10 on 2025-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='section',
            field=models.CharField(choices=[('general', 'General'), ('bookings', 'Bookings'), ('events', 'Events'), ('gallery', 'Gallery'), ('categories', 'Categories'), ('support', 'Support')], default='general', max_length=20),
        ),
    ]
