# Generated by Django 4.2.8 on 2025-04-04 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_reviewlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_updated', 'Booking Updated'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('user_registered', 'User Registered'), ('user_updated', 'User Updated'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_deleted', 'Event Deleted'), ('subevent_created', 'Subevent Created'), ('subevent_updated', 'Subevent Updated'), ('subevent_deleted', 'Subevent Deleted'), ('gallery_updated', 'Gallery Updated'), ('message_sent', 'Message Sent'), ('review_posted', 'Review Posted'), ('admin_action', 'Admin Action'), ('newsletter_subscription', 'Newsletter Subscription')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
