# Generated by Django 4.2.8 on 2025-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_mailersend_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_updated', 'Booking Updated'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('user_registered', 'User Registered'), ('user_updated', 'User Updated'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_deleted', 'Event Deleted'), ('subevent_created', 'Subevent Created'), ('subevent_updated', 'Subevent Updated'), ('subevent_deleted', 'Subevent Deleted'), ('gallery_updated', 'Gallery Updated'), ('message_sent', 'Message Sent'), ('review_posted', 'Review Posted'), ('admin_action', 'Admin Action'), ('email_subscription', 'Email Subscription')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
