services:
  # A Django web service
  - type: web
    name: myday
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myday.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myday_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.9

databases:
  - name: myday_db
    databaseName: myday
    user: myday
