services:
  # A Django web service
  - type: web
    name: myday
    env: python
    buildCommand: "./build.sh"
    startCommand: "python ensure_persistence.py && gunicorn myday.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: myday-postgres
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "myday.settings"
    disk:
      name: myday_data
      mountPath: /data
      sizeGB: 1

databases:
  - type: postgres
    name: myday-postgres
    plan: starter
    ipAllowList: []  # Allow all connections
