services:
  # A Django web service
  - type: web
    name: myday
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myday.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "myday.settings"
      - key: WEB_CONCURRENCY
        value: 4
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
