services:
  # A Django web service
  - type: web
    name: myday
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myday.wsgi:application"
    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myday_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "myday.settings"

databases:
  - name: myday_db
    databaseName: myday
    user: myday
    plan: free
